### ISSUE TITLE
No module named 'utilities'

### ISSUE THREAD

**Issue by altcnews** [FaGuoMa/bitmex-mm-lomond#1]
Hi There,
I got this following error while running this:

Traceback (most recent call last):
 File "trader/trader.py", line 9, in <module>
   from utilities import generate_nonce, generate_signature_bitmex,
build_requests, findItemByKeys, avg_price_inv
ModuleNotFoundError: No module named 'utilities'

Could you please help?
Thanks & Regards.

**Comment by FaGuoMa** [comment]
I believe this is the joy of virtual environments and whatnots. Assuming you have cloned into your home (`/home/atcnews/bitmex-mm-lomond/` for example, can you try either:  
1. adding the following lines at the top of `trader.py` :
```python
import sys
sys.path.append("/home/atcnews/bitmex-mm-lomond/")
```
2. Alternatively, I have moved the file at root and that should work

*Note*: I suspect the reason is something I do locally which might be useful to some: I tend to reuse a lot of code across projects (libraries e.g.) and an easy way to enable easy import is to add a `whatever.pth` (only extension is relevant) to the `/you/virtual/env/path/lib/python3.6/site-packages` folder. The `pth` file would include lines with path of projects your work on (without trailing slash). [example stackoverflow](https://stackoverflow.com/questions/15208615/using-pth-files)

**Comment by altcnews** [comment]
Hi dev,
thanks for replying...it is running (seems like), but i need to re configure the agent as you said it is bit dodgy :)

I got this error while running this few minutes a go, it might be my ip is banned from bitmex

47:52.926|WARNING |devmm     |  !!!!!!! YOU ARE RUNNING IN PROD !!!!!!!
Traceback (most recent call last):
 File "trader.py", line 472, in <module>
   c.boot(conf="prod", symbol_list=['XBTUSD'])
 File "trader.py", line 192, in boot
   min_remain=30, test=test)
 File "/home/ubuntu/lomond/orders.py", line 977, in __init__
   self.client = bitmex.bitmex(test=test, api_key=self.apiKey,
api_secret=self.apiSecret)
 File "/usr/local/lib/python3.6/dist-packages/bitmex.py", line 35, in
bitmex
   return SwaggerClient.from_url(spec_uri, config=config,
http_client=request_client)
 File "/usr/local/lib/python3.6/dist-packages/bravado/client.py", line
96, in from_url
   spec_dict = loader.load_spec(spec_url)
 File "/usr/local/lib/python3.6/dist-
packages/bravado/swagger_model.py", line 105, in load_spec
   self.request_headers,
 File "/usr/local/lib/python3.6/dist-packages/bravado/http_future.py", 
line 281, in result
   raise make_http_exception(response=incoming_response)
bravado.exception.HTTPForbidden: 403 Forbidden

Updated:
Got it running on testnet, but how to solve this?

50:50.730|DEBUG   |Agent MM  |  q & prices : bids [] 
asks [{'price': 5271.5, 't_market': 174.375905, 'q_pos': 0.751}]
50:50.731|DEBUG   |Agent MM  |  cur orders {'bids': [], 'asks':
[{'symbol': 'XBTUSD', 'price': 5271.5, 'orderQty': -1000, 'clOrdID':
'7af83069-62f2-4aee-b65e-3ed58f98e0d6', 'execInst':
'ParticipateDoNotInitiate', 't_market': 174.375905, 'q_pos': 0.751}]}
50:50.731|WARNING |lomond    |  disconnecting websocket
Traceback (most recent call last):
 File "trader.py", line 474, in <module>
   c.run()
 File "trader.py", line 434, in run
   self.agent.on_l2()
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 466, in on_l2
   self.determine_state()
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 185, in
determine_state
   self.agent_perform(indi_dict=indi_dict,
curr_inventory=curr_inventory)
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 235, in
agent_perform
   bid_post_pxs=bid_post_pxs)
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 323, in
evaluate_outstanding_orders
   bb = sorted(cur_orders['bids'], key= flt_fun, reverse=True)[0]
IndexError: list index out of range

Appreciate for your kindly help.
Thanks & Regards.

**Comment by FaGuoMa** [comment]
First of all, I'll close this issue with that since your main issue seems solved. To you various points:
- 403: indeed you're banned. Note that it might happen on both testnet and mainnet, but you're running in prod (which you really shouldn't for now, especially to adjust ban sensitivity
- deadman is just to cancel orders if you loose connectivity. It's a swithc periodically reactivated
- the quote_size is actually large enough (I think) not to trigger the spam warning from bitmex (I believe they actually mention `spamspamspam` in headers when triggered), but your max inventory needs to be higher (probably 4x-5x min)


The real issue as I remember is on the best bid/ask: the q_ratio is an limit besides which you don't want to keep the order up (Mex is FIFO and you don't want to be the last one at a give rung). However, depending on the security (and testnet) there might not be much action at times. So, you can increase grace period parameter to, says, 10 seconds or so and it should limit the 'flicker' at the best b/a.

Update: please make another issue for your other bug (stemming from line 316 featuring an `or`) as it is unrelated

**Comment by altcnews** [comment]
Hi Dev,
Thanks.

Indeed, i still got the list index out of range after making the max of inventory higher.

Really appreciate for your great work.
Regards.

**Comment by FaGuoMa** [comment]
This issue is closed. 
Please help me keep this thing manageable and tidy by creating a new issue
